In [3]:
import numpy as np
import cv2

[[1029  416   34   83]
 [1029  416   35   84]
 [1029  416   35   84]
 [ 967  419   43   69]
 [ 967  419   44   69]
 [ 908  422   53   64]
 [ 908  422   53   64]
 [ 908  422   54   64]
 [ 907  422   55   65]
 [ 845  424   57   60]
 [ 845  424   57   60]
 [ 845  424   58   61]
 [ 803  218   59   64]
 [ 773  315   77   71]
 [ 773  315   77   71]
 [ 773  315   77   71]
 [ 773  315   77   72]
 [ 773  315   77   72]
 [ 267  175   93  105]
 [ 267  174   93  106]
 [ 267  174   93  106]
 [ 267  174   93  106]
 [ 267  174   93  106]
 [ 267  173   93  107]
 [ 793  424   47   71]
 [ 793  424   47   71]
 [ 792  423   48   72]
 [ 792  423   48   72]
 [ 792  422   48   73]
 [ 792  422   48   73]
 [ 792  422   48   73]
 [ 792  422   48   73]
 [ 792  422   48   73]
 [ 377  197   63   81]
 [ 377  196   63   83]
 [ 377  196   63   83]
 [ 377  196   63   83]
 [ 377  196   64   83]
 [ 377  196   64   83]
 [ 377  196   64   83]
 [ 377  196   64   83]
 [ 377  196   64   83]
 [ 792  422   48   73]
 [ 454  198

-1

-1